networks:
  backend:


volumes:
  mongodb_data:
  stspgadmin:
  stsdb:


services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: unless-stopped
    networks:
      - backend
    environment:
      - KAFKA_CLUSTER_ID=your-cluster-id
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/tmp/kraft-combined-logs
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    volumes:
      - ./kafka-data:/bitnami/kafka

  mongodb:
    container_name: social_db
    image: mongo:5.0.15
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  stiktifybackend:
    container_name: stiktify-backend
    build:
      context: ./Stiktify-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mongodb
      - kafka
    environment:
      - NODE_ENV=production
    command: npm run start:prod
    env_file: Stiktify-backend/.env

  pgadmin:
    container_name: stiktify-shop-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@ecommerce.store}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - stspgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped

  ssdb:
    container_name: shop-data
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=shopdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - stsdb:/var/lib/postgresql/data

  stiktifyshop:
    container_name: stiktify-shop-backend
    image: ${DOCKER_REGISTRY-}stiktifyshop
    ports:
      - "8000:8081"
      - "8088:8080"
    build:
      context: .
      dockerfile: StiktifyShop/Dockerfile
    restart: unless-stopped
    depends_on:
      - ssdb
    networks:
      - backend
