networks:
  backend:

volumes:
  mongodb_data_container:
  sspgadmin:
  ssuserdata:
  ssproductdata:
  ssorderdata:
  sspurchasedata:

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - backend
    environment:
      - KAFKA_CLUSTER_ID=your-cluster-id
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/tmp/kraft-combined-logs
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    volumes:
      - ./kafka-data:/bitnami/kafka

  mongodb:
    container_name: social_db
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend

  stiktifybackend:
    container_name: stiktify-backend
    build:
        context: ./Stiktify-backend
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mongodb
      - kafka
    environment:
      - NODE_ENV=production
    command: npm run start:prod
    env_file: Stiktify-backend/.env

  stiktifyshopbackend:
    container_name: stiktify-shop-backend
    image: ${DOCKER_REGISTRY-}stiktifyshopbackend
    ports:
        - "8000:8081"
    build:
      context: .
      dockerfile: StiktifyShopBackend/Dockerfile
    restart: unless-stopped
    depends_on:
        - grpcserviceuser
    networks:
        - backend

  pgadmin:
    container_name: stiktify-shop-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@ecommerce.store}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - sspgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped

  ssuserdata:
    container_name: user-data
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - ssuserdata:/var/lib/postgresql/data

  ssproductdata:
    container_name: product-data
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - ssproductdata:/var/lib/postgresql/data

  ssorderdata:
    container_name: order-data
    image: postgres
    ports:
      - "5434:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - ssorderdata:/var/lib/postgresql/data

  sspurchasedata:
    container_name: purchase-data
    image: postgres
    ports:
      - "5435:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=purchasedb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - sspurchasedata:/var/lib/postgresql/data
  
  grpcserviceuser:
    container_name: grpc-service-user
    image: ${DOCKER_REGISTRY-}grpcserviceuser
    networks:
        - backend
    ports:
        - "15000:8080"
    build:
      context: .
      dockerfile: GrpcServiceUser/Dockerfile
    depends_on:
        - ssuserdata

  grpcserviceproduct:
    container_name: grpc-service-product
    image: ${DOCKER_REGISTRY-}grpcserviceproduct
    networks:
        - backend
    ports:
        - "15001:8080"
    build:
      context: .
      dockerfile: GrpcServiceProduct/Dockerfile
    depends_on:
        - ssproductdata


  grpcserviceorder:
    container_name: grpc-service-order
    image: ${DOCKER_REGISTRY-}grpcserviceorder
    ports:
        - "15002:8080"
    networks:
        - backend
    build:
      context: .
      dockerfile: GrpcServiceOrder/Dockerfile
    depends_on:
        - ssorderdata


  grpcservicepurchase:
    container_name: grpc-service-purchase
    image: ${DOCKER_REGISTRY-}grpcservicepurchase
    ports:
        - "15003:8080"
    networks:
        - backend
    build:
      context: .
      dockerfile: GrpcServicePurchase/Dockerfile
    depends_on:
        - sspurchasedata

